# This workflow will release a new developer build version on github

name: Auto release developer-build

on:
  push:
    branches: [ ExperimentalTabMode ] 
  workflow_dispatch:
    inputs:
      version:
        description: 'Release "milestone" "majore" "minore" or "dev"'
        required: true
        default: 'dev'

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}


    - name: Increase Version in manifest.json
      shell: cmd
      run: |

        Get-Command "jq.exe"
        jq.exe --version

        echo do some git configuration
        git config user.name github-actions
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git status
        git checkout ExperimentalTabMode
        git status

        echo extract version numbers
        jq.exe (.version^|split(\".\")^|map(tonumber)^|.[0]) < plugin/manifest.json > milestone_version.txt
        jq.exe (.version^|split(\".\")^|map(tonumber)^|.[1]) < plugin/manifest.json > majore_version.txt
        jq.exe (.version^|split(\".\")^|map(tonumber)^|.[2]) < plugin/manifest.json > minore_version.txt
        jq.exe (.version^|split(\".\")^|map(tonumber)^|.[3]) < plugin/manifest.json > dev_version.txt
        
        set /p var_mil=<milestone_version.txt
        set /p var_maj=<majore_version.txt
        set /p var_min=<minore_version.txt
        set /p var_dev=<dev_version.txt
        jq.exe -r (.version^|split(\".\")^|map(tonumber)^|(.[0]^|=%var_mil%)^|(.[1]^|=%var_maj%)^|(.[2]^|=%var_min%)^|(.[3]^|=0)^|map(tostring)^|join(\".\")) < plugin/manifest.json > old_change_log_version.txt

        if [[ "milestone" == "$version" ]]; then
          jq.exe tonumber+1 < milestone_version.txt > milestone_version.txt
          echo 0 > majore_version.txt
          echo 0 > minore_version.txt
          echo 0 > dev_version.txt
        else
          if [[ "majore" == "$version" ]]; then
            jq.exe tonumber+1 < majore_version.txt > majore_version.txt
            echo 0 > minore_version.txt
            echo 0 > dev_version.txt
          else
            if [[ "minore" == "$version" ]]; then
              jq.exe tonumber+1 < minore_version.txt > minore_version.txt
              echo 0 > dev_version.txt
            else
              jq.exe tonumber+1 < dev_version.txt > dev_version.txt
            fi
          fi
        fi

        set /p var_mil=<milestone_version.txt
        set /p var_maj=<majore_version.txt
        set /p var_min=<minore_version.txt
        set /p var_dev=<dev_version.txt

        echo save complete version number in new_version.txt
        jq.exe (.version^|split(\".\")^|map(tonumber)^|(.[0]^|=%var_mil%)^|(.[1]^|=%var_maj%)^|(.[2]^|=%var_min%)^|(.[3]^|=%var_dev%)^|map(tostring)^|join(\".\")) < plugin/manifest.json > new_version.txt
        set /p var_build=<new_version.txt

        echo save new_manifest.json with new version number
        jq.exe (.version^|=\"%var_build%\") plugin/manifest.json > new_manifest.json
        echo move new_manifest.json to manifest.json
        move /y new_manifest.json plugin/manifest.json

        echo cleanup new_version.txt
        jq.exe -r . new_version.txt > new_clean_version.txt
        
        echo npm install/ run
    - run: npm install
    - run: npm run lint
    
    - name: commit/ push git changes
      shell: cmd
      run: |
        echo commit git changes
        git add plugin/manifest.json
        git commit -m "Auto version bump for Version %var_build%"
        git push
        git rev-parse --verify HEAD > commit_sha.txt

        
    - name: Release latest developer build
      shell: cmd
      run: |
        
        set /p var_build=<new_clean_version.txt
        set /p var_old_change_log_version=<old_change_log_version.txt
        set /p var_commit_sha=<commit_sha.txt

        if [[ "0.0.0.0" == "%var_old_change_log_version%" ]]; then
          set var_old_change_log_version=0.0.0.160
        fi

        echo zip release files
        cd eslint
        tar -a -c -f WebToEpub-developer-build-%Build%.zip WebToEpub%var_build%.xpi WebToEpub%var_build%.zip
        cd ..

        echo rename release files
        cd eslint
        move /y WebToEpub%var_build%.xpi WebToEpub%var_build%.Firefox.zip
        move /y WebToEpub%var_build%.zip WebToEpub%var_build%.Chrome.zip
        cd ..
        
        
        if [[ "milestone" == "$version" ]] || [[ "majore" == "$version" ]] || [[ "minore" == "$version" ]]; then

          echo Create release notes.
          echo ## What's Changed> output.txt
          echo.>> output.txt
          echo placeholder >> output.txt
          echo.>> output.txt
          echo ## New Contributors>> output.txt
          echo.>> output.txt
          echo **Full Changelog**: https://github.com/dteviot/WebToEpub/compare/%var_old_change_log_version%...%var_commit_sha% >> output.txt

          echo create developer-build release:
          gh release create var_build -p -t "Release %var_build%" --target "ExperimentalTabMode" -F output.txt
          
          echo add files to release.
          gh release upload developer-build eslint/WebToEpub%var_build%.Firefox.zip
          gh release upload developer-build eslint/WebToEpub%var_build%.Chrome.zip
        else
        
          echo Create developer-build release notes.
          echo Latest developer build of WebToEpub with the latest fixes. > output.txt
          echo To install the Addon pick the file suitable for you, >> output.txt
          echo * WebToEpub%Build%.Firefox.zip for Firefox >> output.txt
          echo * WebToEpub%Build%.Chrome.zip for Chrome >> output.txt
          echo.>> output.txt
          echo follow the [How to install from Source (for people who are not developers)](https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers) instructions to install it.>> output.txt
          echo.>> output.txt
          echo **Full Changelog**: https://github.com/dteviot/WebToEpub/compare/%var_old_change_log_version%...%var_commit_sha% >> output.txt

          echo delete old developer-build release:
          gh release delete developer-build --cleanup-tag

          echo create developer-build release:
          gh release create developer-build -p -t "Latest developer build" --target "ExperimentalTabMode" -F output.txt
          
          echo add files to release.
          gh release upload developer-build eslint/WebToEpub%var_build%.Firefox.zip
          gh release upload developer-build eslint/WebToEpub%var_build%.Chrome.zip
        fi
      env:
          GH_TOKEN: ${{ github.token }}